# Starten mit dem Alpine-Image als Basis
FROM alpine:latest

# Aktualisieren und Installieren von notwendigen Paketen
RUN apk update && \
    apk add openjdk11 iproute2 iperf3 tcpdump netcat-openbsd iputils

# Setzen des Arbeitsverzeichnisses im Container
WORKDIR /app

# Kopieren nur der BootstrapServer.java-Datei in das Arbeitsverzeichnis
COPY BootstrapServer.java /app/

# Kompilieren des Java-Programms
RUN javac BootstrapServer.java

